# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class HomeClass(object):
    def setupUi(self, Main_page):
        Main_page.setObjectName("Main_page")
        Main_page.resize(503, 358)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Main_page.setWindowIcon(icon)
        Main_page.setStyleSheet("QMainWindow {\n"
"    border: solid white 5px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Main_page)
        self.centralwidget.setStyleSheet("QWidget#centralwidget {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:1, stop:0.00568182 rgba(170, 85, 127, 255), stop:0.988636 rgba(109, 25, 27, 255), stop:1 rgba(66, 164, 255, 255));\n"
"}\n"
"  \n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.Home_page = QtWidgets.QGroupBox(self.centralwidget)
        self.Home_page.setGeometry(QtCore.QRect(180, 1, 322, 356))
        self.Home_page.setStyleSheet("QGroupBox {\n"
"    background-color: #FFF;\n"
"    border: none;\n"
"}\n"
"  \n"
"")
        self.Home_page.setTitle("")
        self.Home_page.setObjectName("Home_page")
        self.Slideshow = QtWidgets.QLabel(self.Home_page)
        self.Slideshow.setGeometry(QtCore.QRect(20, 10, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.Slideshow.setFont(font)
        self.Slideshow.setStyleSheet("")
        self.Slideshow.setAlignment(QtCore.Qt.AlignCenter)
        self.Slideshow.setObjectName("Slideshow")
        self.Author = QtWidgets.QLabel(self.Home_page)
        self.Author.setGeometry(QtCore.QRect(205, 340, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        self.Author.setFont(font)
        self.Author.setAcceptDrops(False)
        self.Author.setStyleSheet("")
        self.Author.setScaledContents(False)
        self.Author.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Author.setObjectName("Author")
        self.groupBox = QtWidgets.QGroupBox(self.Home_page)
        self.groupBox.setGeometry(QtCore.QRect(277, 3, 43, 20))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.Mini = QtWidgets.QPushButton(self.groupBox)
        self.Mini.setGeometry(QtCore.QRect(3, 2, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Mini.setFont(font)
        self.Mini.setStyleSheet("QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(72, 72, 72);\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(131, 131, 131);\n"
"    border-radius: 8px;\n"
"}")
        self.Mini.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("static/minimum-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Mini.setIcon(icon1)
        self.Mini.setIconSize(QtCore.QSize(12, 12))
        self.Mini.setObjectName("Mini")
        self.Exit = QtWidgets.QPushButton(self.groupBox)
        self.Exit.setGeometry(QtCore.QRect(23, 2, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Exit.setFont(font)
        self.Exit.setStyleSheet("QPushButton:hover:!pressed\n"
"{\n"
"    background-color: rgb(107, 0, 0);\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(170, 85, 0);\n"
"    border-radius: 8px;\n"
"}")
        self.Exit.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("static/times-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Exit.setIcon(icon2)
        self.Exit.setIconSize(QtCore.QSize(12, 12))
        self.Exit.setObjectName("Exit")
        self.Image0 = QtWidgets.QLabel(self.Home_page)
        self.Image0.setGeometry(QtCore.QRect(40, 60, 250, 250))
        self.Image0.setStyleSheet("")
        self.Image0.setText("")
        self.Image0.setObjectName("Image0")
        self.Package = QtWidgets.QLabel(self.Home_page)
        self.Package.setGeometry(QtCore.QRect(40, 320, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Package.setFont(font)
        self.Package.setObjectName("Package")
        self.Image = QtWidgets.QLabel(self.Home_page)
        self.Image.setGeometry(QtCore.QRect(150, 320, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Image.setFont(font)
        self.Image.setObjectName("Image")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(20, 330, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Title.setFont(font)
        self.Title.setStyleSheet("QLabel#Title {\n"
"    color: #fff;\n"
"}")
        self.Title.setScaledContents(True)
        self.Title.setWordWrap(False)
        self.Title.setIndent(0)
        self.Title.setObjectName("Title")
        self.Icon = QtWidgets.QLabel(self.centralwidget)
        self.Icon.setGeometry(QtCore.QRect(-5, 333, 21, 21))
        self.Icon.setText("")
        self.Icon.setPixmap(QtGui.QPixmap("static/logo.png"))
        self.Icon.setScaledContents(True)
        self.Icon.setObjectName("Icon")
        self.Description = QtWidgets.QLabel(self.centralwidget)
        self.Description.setGeometry(QtCore.QRect(20, 343, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(4)
        font.setBold(False)
        font.setWeight(50)
        self.Description.setFont(font)
        self.Description.setStyleSheet("QLabel#Description {\n"
"    color: #fff;\n"
"}")
        self.Description.setObjectName("Description")
        self.SaveDir = QtWidgets.QLabel(self.centralwidget)
        self.SaveDir.setGeometry(QtCore.QRect(10, 300, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Candara Light")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.SaveDir.setFont(font)
        self.SaveDir.setStyleSheet("QLabel {\n"
"      background-color:  #ddd;\n"
"      border: none; \n"
"    color: #000;\n"
"    border-radius: 5px;\n"
"}")
        self.SaveDir.setScaledContents(False)
        self.SaveDir.setWordWrap(False)
        self.SaveDir.setIndent(50)
        self.SaveDir.setObjectName("SaveDir")
        self.SaveFolder = QtWidgets.QPushButton(self.centralwidget)
        self.SaveFolder.setGeometry(QtCore.QRect(10, 300, 38, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.SaveFolder.setFont(font)
        self.SaveFolder.setStyleSheet("QPushButton:hover:!pressed\n"
"{\n"
"      \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(28, 64, 109, 255), stop:0.988636 rgba(97, 153, 173, 255), stop:1 rgba(66, 164, 255, 255));\n"
"}\n"
"QPushButton {\n"
"    \n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(64, 64, 64, 255));\n"
"    border: none; \n"
"    color: white;\n"
"    border-bottom-left-radius : 5px;\n"
"    border-top-left-radius : 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(28, 64, 109, 255), stop:0.988636 rgba(97, 153, 173, 255), stop:1 rgba(66, 164, 255, 255));\n"
"}")
        self.SaveFolder.setIconSize(QtCore.QSize(14, 14))
        self.SaveFolder.setObjectName("SaveFolder")
        self.TagPhotos = QtWidgets.QPushButton(self.centralwidget)
        self.TagPhotos.setGeometry(QtCore.QRect(4, 60, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.TagPhotos.setFont(font)
        self.TagPhotos.setStyleSheet("QPushButton:hover:!pressed {\n"
"    border: none;\n"
"    \n"
"    background-color: rgba(85, 0, 0, 80);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    background-color: none;\n"
"    color: white;\n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"}\n"
"  \n"
"QPushButton:disabled {\n"
"    color: gray;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("static/download-arrow-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TagPhotos.setIcon(icon3)
        self.TagPhotos.setIconSize(QtCore.QSize(16, 16))
        self.TagPhotos.setObjectName("TagPhotos")
        self.Uploaded = QtWidgets.QPushButton(self.centralwidget)
        self.Uploaded.setGeometry(QtCore.QRect(4, 90, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Uploaded.setFont(font)
        self.Uploaded.setStyleSheet("QPushButton:hover:!pressed {\n"
"    border: none;\n"
"    \n"
"    background-color: rgba(85, 0, 0, 80);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    background-color: none;\n"
"    color: white;\n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"}\n"
"  \n"
"QPushButton:disabled {\n"
"    color: gray;\n"
"}\n"
"\n"
"")
        self.Uploaded.setIcon(icon3)
        self.Uploaded.setIconSize(QtCore.QSize(16, 16))
        self.Uploaded.setObjectName("Uploaded")
        self.Name = QtWidgets.QPushButton(self.centralwidget)
        self.Name.setGeometry(QtCore.QRect(4, 30, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Name.setFont(font)
        self.Name.setStyleSheet("QPushButton:hover:!pressed {\n"
"    border: none;\n"
"    \n"
"    background-color: rgba(85, 0, 0, 80);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    background-color: none;\n"
"    color: white;\n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"}\n"
"  \n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("static/avatar-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Name.setIcon(icon4)
        self.Name.setIconSize(QtCore.QSize(16, 16))
        self.Name.setObjectName("Name")
        self.Stop0 = QtWidgets.QPushButton(self.centralwidget)
        self.Stop0.setGeometry(QtCore.QRect(153, 68, 16, 16))
        self.Stop0.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 80);\n"
"}")
        self.Stop0.setText("")
        self.Stop0.setIcon(icon2)
        self.Stop0.setObjectName("Stop0")
        self.Stop1 = QtWidgets.QPushButton(self.centralwidget)
        self.Stop1.setGeometry(QtCore.QRect(153, 98, 16, 16))
        self.Stop1.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 80);\n"
"}")
        self.Stop1.setText("")
        self.Stop1.setIcon(icon2)
        self.Stop1.setObjectName("Stop1")
        self.SaveAs = QtWidgets.QLabel(self.centralwidget)
        self.SaveAs.setGeometry(QtCore.QRect(10, 280, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        self.SaveAs.setFont(font)
        self.SaveAs.setStyleSheet("QLabel {\n"
"    color: #fff;\n"
"}")
        self.SaveAs.setObjectName("SaveAs")
        self.ProfileInput = QtWidgets.QLineEdit(self.centralwidget)
        self.ProfileInput.setGeometry(QtCore.QRect(10, 250, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        self.ProfileInput.setFont(font)
        self.ProfileInput.setStyleSheet("QLineEdit {\n"
"      background-color:  #ddd;\n"
"      border: none; \n"
"    color: #000;\n"
"    border-radius: 5px;\n"
"    padding-left: 5px;\n"
"}")
        self.ProfileInput.setText("")
        self.ProfileInput.setCursorPosition(0)
        self.ProfileInput.setObjectName("ProfileInput")
        self.ProfileUrl = QtWidgets.QLabel(self.centralwidget)
        self.ProfileUrl.setGeometry(QtCore.QRect(10, 230, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        self.ProfileUrl.setFont(font)
        self.ProfileUrl.setStyleSheet("QLabel {\n"
"    color: #fff;\n"
"}")
        self.ProfileUrl.setObjectName("ProfileUrl")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 171, 161, 58))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(4)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    border: 1px solid white;\n"
"    border-radius: 3px;\n"
"    padding: 3px;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        Main_page.setCentralWidget(self.centralwidget)

        self.retranslateUi(Main_page)
        QtCore.QMetaObject.connectSlotsByName(Main_page)

    def retranslateUi(self, Main_page):
        _translate = QtCore.QCoreApplication.translate
        Main_page.setWindowTitle(_translate("Main_page", "Facekup - Download everything"))
        self.Slideshow.setText(_translate("Main_page", "SLIDESHOW"))
        self.Author.setText(_translate("Main_page", "www.nguyentrieuphong.com "))
        self.Package.setText(_translate("Main_page", "Package: 00"))
        self.Image.setText(_translate("Main_page", "Image: 00"))
        self.Title.setText(_translate("Main_page", "Facekup"))
        self.Description.setText(_translate("Main_page", "Facebook image backup version 1.0.19"))
        self.SaveDir.setText(_translate("Main_page", "C:\\"))
        self.SaveFolder.setText(_translate("Main_page", "Save as"))
        self.TagPhotos.setText(_translate("Main_page", "Uploaded photos"))
        self.Uploaded.setText(_translate("Main_page", "Tagged photos"))
        self.Name.setText(_translate("Main_page", "Name"))
        self.SaveAs.setText(_translate("Main_page", "Save images at:"))
        self.ProfileInput.setPlaceholderText(_translate("Main_page", " Default is your user name"))
        self.ProfileUrl.setText(_translate("Main_page", "Friend\'s user name:"))
        self.label.setText(_translate("Main_page", "<html><head/><body><p>Now, you can download your friend\'s photos by adding their user name or user id below! Visit your friend\'s profile and copy user name or user id on the url.<br/>For example: <br/>1. www.facebook.com/<span style=\" font-weight:600;\">phong.gtvt<br/>- </span>you need import <span style=\" font-weight:600;\">phong.gtvt<br/></span>2. www.facebook.com/profile.php?id=<span style=\" font-weight:600;\">1000123456789 <br/>- </span>you need import <span style=\" font-weight:600;\">1000123456789</span></p></body></html>"))
